package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cfclient generated by hbm2java
 */
public class Cfclient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer code;
	private String prefix;
	private String glycemie;
	private String aghbs;
	private String categorie;
	private String prenomnom;
	private String nomprenom;
	private String categoriEtoile;
	private String nom;
	private String prenom;
	private boolean ddgCorigee;
	private String cnss;
	private String sexe;
	private String civil;
	private String dateNaiss;
	private String rue;
	private String village;
	private String pays;
	private String telephone;
	private String notes;
	private String typCons;
	private int nbCons;
	private String dateCons;
	private String datesaisie;
	private String ant11;
	private Integer dpr;
	private Date mariage;
	private String consang;
	private String dureeReg;
	private String regles;
	private String dysmenorhe;
	private String mastodynie;
	private Integer menopose;
	private String ant3;
	private String dateFr;
	private String resultFr;
	private String ddr;
	private boolean spanio;
	private String ddg;
	private String dateMoyen;
	private String moyen;
	private int gestite;
	private int partie;
	private Integer gviv;
	private Integer fviv;
	private int cesar;
	private String codePost;

	private String telephone2;
	private String telC;
	private String gsmC;
	private String gsm1;
	private String gsm2;
	private String eMailP;
	private String eMailC;
	private String nomC;
	private String prenomC;
	private String taille;
	private String poids;
	private String gs;
	private String rh;
	private String dateFrotti;
	private String resultatFrotti;
	private String dateNaissC;
	private String allergie;
	private String notes2;
	private String dernierVisite;
	private String assurance1;
	private String assurance2;
	private String remarque;
	private String tPrevu;
	private String tActuel;
	private String toxo;
	private String tpha;
	private String rubeole;
	private int nbrGarcon;
	private int nbrFille;
	private String cycleType;
	private String regleType;
	private String cycle;
	private String prenomNomConjoint;
	private Ville ville;
	private Clinique clinique;
	private Profession professionByProfesscp;
	private Docteur doctor;
	private Profession professionByProfessp;
	private Set<HistoriqueCertif> historiqueCertifs = new HashSet<HistoriqueCertif>();
	private Set<AntMedCfclient> antMed = new HashSet<AntMedCfclient>(0);
	private Set<AntFamCfclient> antFam = new HashSet<AntFamCfclient>(0);
	private Set<AntChirCfclient> antChir = new HashSet<AntChirCfclient>(0);
	private Set<Salle> salles = new HashSet<Salle>(0);
	private Set<HistoriquePatient> histoirs = new HashSet<HistoriquePatient>(0);
	private Set<Sterile> steriles = new HashSet<Sterile>(0);
	private Set<HistoriqueGross> historiqueGrosss = new HashSet<HistoriqueGross>(
			0);
	private Set<Contraception> contraceptions = new HashSet<Contraception>(0);

	private String professionP;
	private String professionC;

	private boolean archive;

	public boolean isArchive() {
		return archive;
	}

	public void setArchive(boolean archive) {
		this.archive = archive;
	}

	public String getCycle() {
		return cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	public String getRegleType() {
		return regleType;
	}

	public void setRegleType(String regleType) {
		this.regleType = regleType;
	}

	public String getCycleType() {
		return cycleType;
	}

	public void setCycleType(String cyleType) {
		this.cycleType = cyleType;
	}

	;

	public Set<HistoriqueCertif> getHistoriqueCertifs() {
		return historiqueCertifs;
	}

	public void setHistoriqueCertifs(Set<HistoriqueCertif> historiqueCertifs) {
		this.historiqueCertifs = historiqueCertifs;
	}

	public String getNotes2() {
		return notes2;
	}

	public void setNotes2(String notes2) {
		this.notes2 = notes2;
	}

	public int getNbrGarcon() {
		return nbrGarcon;
	}

	public void setNbrGarcon(int nbrGarcon) {
		this.nbrGarcon = nbrGarcon;
	}

	public int getNbrFille() {
		return nbrFille;
	}

	public void setNbrFille(int nbrFille) {
		this.nbrFille = nbrFille;
	}

	public String gettPrevu() {
		return tPrevu;
	}

	public void settPrevu(String tPrevu) {
		this.tPrevu = tPrevu;
	}

	public String gettActuel() {
		return tActuel;
	}

	public void settActuel(String tActuel) {
		this.tActuel = tActuel;
	}

	public String getToxo() {
		return toxo;
	}

	public void setToxo(String toxo) {
		this.toxo = toxo;
	}

	public String getTpha() {
		return tpha;
	}

	public void setTpha(String tpha) {
		this.tpha = tpha;
	}

	public String getRubeole() {
		return rubeole;
	}

	public void setRubeole(String rubeole) {
		this.rubeole = rubeole;
	}

	public String getRemarque() {
		return remarque;
	}

	public void setRemarque(String remarque) {
		this.remarque = remarque;
	}

	public String getAssurance1() {
		return assurance1;
	}

	public void setAssurance1(String assurance1) {
		this.assurance1 = assurance1;
	}

	public String getAssurance2() {
		return assurance2;
	}

	public void setAssurance2(String assurance2) {
		this.assurance2 = assurance2;
	}

	public String getDernierVisite() {
		return dernierVisite;
	}

	public void setDernierVisite(String dernierVisite) {
		this.dernierVisite = dernierVisite;
	}

	public Set<AntFamCfclient> getAntFam() {
		return antFam;
	}

	public void setAntFam(Set<AntFamCfclient> antFam) {
		this.antFam = antFam;
	}

	public Set<AntChirCfclient> getAntChir() {
		return antChir;
	}

	public void setAntChir(Set<AntChirCfclient> antChir) {
		this.antChir = antChir;
	}

	public Set<AntMedCfclient> getAntMed() {

		return antMed;
	}

	public void setAntMed(Set<AntMedCfclient> antMed) {
		this.antMed = antMed;
	}

	public String getAllergie() {
		return allergie;
	}

	public void setAllergie(String allergie) {
		this.allergie = allergie;
	}

	public Set<HistoriquePatient> getHistoirs() {
		return histoirs;
	}

	public void setHistoirs(Set<HistoriquePatient> histoirs) {
		this.histoirs = histoirs;
	}

	public String getProfessionP() {
		return professionP;
	}

	public void setProfessionP(String professionP) {
		this.professionP = professionP;
	}

	public String getProfessionC() {
		return professionC;
	}

	public void setProfessionC(String professionC) {
		this.professionC = professionC;
	}

	public String getVillage() {
		return village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	public Set<Contraception> getContraceptions() {
		return contraceptions;
	}

	public void setContraceptions(Set<Contraception> contraceptions) {
		this.contraceptions = contraceptions;
	}

	public Set<HistoriqueGross> getHistoriqueGrosss() {
		return historiqueGrosss;
	}

	public void setHistoriqueGrosss(Set<HistoriqueGross> historiqueGrosss) {
		this.historiqueGrosss = historiqueGrosss;
	}

	public Set<Sterile> getSteriles() {
		return steriles;
	}

	public void setSteriles(Set<Sterile> steriles) {
		this.steriles = steriles;
	}

	public Cfclient() {
	}

	public String getCodePost() {
		return codePost;
	}

	public void setCodePost(String codePost) {
		this.codePost = codePost;
	}

	public String getDateNaissC() {
		return dateNaissC;
	}

	public void setDateNaissC(String dateNaissC) {
		this.dateNaissC = dateNaissC;
	}

	public Integer getCode() {

		return code;
	}

	public void setCode(Integer code) {

		this.code = code;
	}

	public Ville getVille() {
		return ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	public Clinique getClinique() {
		return clinique;
	}

	public void setClinique(Clinique clinique) {
		this.clinique = clinique;
	}

	public Profession getProfessionByProfesscp() {
		return professionByProfesscp;
	}

	public void setProfessionByProfesscp(Profession professionByProfesscp) {
		this.professionByProfesscp = professionByProfesscp;
	}

	public Docteur getDoctor() {
		return doctor;
	}

	public void setDoctor(Docteur doctor) {
		this.doctor = doctor;
	}

	public Profession getProfessionByProfessp() {
		return professionByProfessp;
	}

	public void setProfessionByProfessp(Profession professionByProfessp) {
		this.professionByProfessp = professionByProfessp;
	}

	public String getPrefix() {
		return prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {

		this.nom = nom;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getCnss() {
		return cnss;
	}

	public void setCnss(String cnss) {
		this.cnss = cnss;
	}

	public String getSexe() {
		return sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public String getCivil() {
		return civil;
	}

	public void setCivil(String civil) {
		this.civil = civil;
	}

	public String getDateNaiss() {
		return dateNaiss;
	}

	public void setDateNaiss(String dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	public String getRue() {
		return rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getPays() {
		return pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getTypCons() {
		return typCons;
	}

	public void setTypCons(String typCons) {
		this.typCons = typCons;
	}

	public int getNbCons() {
		return nbCons;
	}

	public void setNbCons(int nbCons) {
		this.nbCons = nbCons;
	}

	public String getDateCons() {
		return dateCons;
	}

	public void setDateCons(String dateCons) {
		this.dateCons = dateCons;
	}

	public String getDatesaisie() {
		return datesaisie;
	}

	public void setDatesaisie(String datesaisie) {
		this.datesaisie = datesaisie;
	}

	public String getAnt11() {
		return ant11;
	}

	public void setAnt11(String ant11) {
		this.ant11 = ant11;
	}

	public Integer getDpr() {
		return dpr;
	}

	public void setDpr(Integer dpr) {
		this.dpr = dpr;
	}

	public Date getMariage() {
		return mariage;
	}

	public void setMariage(Date mariage) {
		this.mariage = mariage;
	}

	public String getConsang() {
		return consang;
	}

	public void setConsang(String consang) {
		this.consang = consang;
	}

	public String getDureeReg() {
		return dureeReg;
	}

	public void setDureeReg(String dureeReg) {
		this.dureeReg = dureeReg;
	}

	public String getRegles() {
		return regles;
	}

	public void setRegles(String regles) {
		this.regles = regles;
	}

	public String getDysmenorhe() {
		return dysmenorhe;
	}

	public void setDysmenorhe(String dysmenorhe) {
		this.dysmenorhe = dysmenorhe;
	}

	public String getMastodynie() {
		return mastodynie;
	}

	public void setMastodynie(String mastodynie) {
		this.mastodynie = mastodynie;
	}

	public Integer getMenopose() {
		return menopose;
	}

	public void setMenopose(Integer menopose) {
		this.menopose = menopose;
	}

	public String getAnt3() {
		return ant3;
	}

	public void setAnt3(String ant3) {
		this.ant3 = ant3;
	}

	public String getDateFr() {
		return dateFr;
	}

	public void setDateFr(String dateFr) {
		this.dateFr = dateFr;
	}

	public String getResultFr() {
		return resultFr;
	}

	public void setResultFr(String resultFr) {
		this.resultFr = resultFr;
	}

	public String getDdr() {
		return ddr;
	}

	public void setDdr(String ddr) {
		this.ddr = ddr;
	}

	public boolean isSpanio() {
		return spanio;
	}

	public void setSpanio(boolean spanio) {
		this.spanio = spanio;
	}

	public String getDdg() {
		return ddg;
	}

	public void setDdg(String ddg) {
		this.ddg = ddg;
	}

	public String getDateMoyen() {
		return dateMoyen;
	}

	public void setDateMoyen(String dateMoyen) {
		this.dateMoyen = dateMoyen;
	}

	public String getMoyen() {
		return moyen;
	}

	public void setMoyen(String moyen) {
		this.moyen = moyen;
	}

	public int getGestite() {
		return gestite;
	}

	public void setGestite(int gestite) {
		this.gestite = gestite;
	}

	public int getPartie() {
		return partie;
	}

	public void setPartie(int partie) {
		this.partie = partie;
	}

	public Integer getGviv() {
		return gviv;
	}

	public String getDateFrotti() {
		return dateFrotti;
	}

	public void setDateFrotti(String dateFrotti) {
		this.dateFrotti = dateFrotti;
	}

	public String getResultatFrotti() {
		return resultatFrotti;
	}

	public void setResultatFrotti(String resultatFrotti) {
		this.resultatFrotti = resultatFrotti;
	}

	public void setGviv(Integer gviv) {
		this.gviv = gviv;
	}

	public Integer getFviv() {
		return fviv;
	}

	public void setFviv(Integer fviv) {
		this.fviv = fviv;
	}

	public int getCesar() {
		return cesar;
	}

	public void setCesar(int cesar) {
		this.cesar = cesar;
	}

	public Set<Salle> getSalles() {
		return salles;
	}

	public void setSalles(Set<Salle> salles) {
		this.salles = salles;
	}

	public String getTelephone2() {
		return telephone2;
	}

	public void setTelephone2(String telephone2) {
		this.telephone2 = telephone2;
	}

	public String getTelC() {
		return telC;
	}

	public void setTelC(String telC) {
		this.telC = telC;
	}

	public String getGsmC() {
		return gsmC;
	}

	public void setGsmC(String gsmC) {
		this.gsmC = gsmC;
	}

	public String getGsm1() {
		return gsm1;
	}

	public void setGsm1(String gsm1) {
		this.gsm1 = gsm1;
	}

	public String getGsm2() {
		return gsm2;
	}

	public void setGsm2(String gsm2) {
		this.gsm2 = gsm2;
	}

	public String geteMailP() {
		return eMailP;
	}

	public void seteMailP(String eMailP) {
		this.eMailP = eMailP;
	}

	public String geteMailC() {
		return eMailC;
	}

	public void seteMailC(String eMailC) {
		this.eMailC = eMailC;
	}

	public String getNomC() {
		return nomC;
	}

	public void setNomC(String nomC) {
		this.nomC = nomC;
	}

	public String getPrenomC() {
		return prenomC;
	}

	public void setPrenomC(String prenomC) {
		this.prenomC = prenomC;
	}

	public String getTaille() {
		return taille;
	}

	public void setTaille(String taille) {
		this.taille = taille;
	}

	public String getPoids() {
		return poids;
	}

	public void setPoids(String poids) {
		this.poids = poids;
	}

	public String getGs() {
		return gs;
	}

	public void setGs(String gs) {
		this.gs = gs;
	}

	public String getRh() {
		return rh;
	}

	public void setRh(String rh) {
		this.rh = rh;
	}

	public String getGlycemie() {
		return glycemie;
	}

	public void setGlycemie(String glycemie) {
		this.glycemie = glycemie;
	}

	public String getAghbs() {
		return aghbs;
	}

	public void setAghbs(String aghbs) {
		this.aghbs = aghbs;
	}

	public String getCategorie() {
		return categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public String getPrenomnom() {
		return prenomnom;
	}

	public void setPrenomnom(String prenomnom) {
		this.prenomnom = prenomnom;
	}

	public String getNomprenom() {
		return nomprenom;
	}

	public void setNomprenom(String nomprenom) {
		this.nomprenom = nomprenom;
	}

	@Override
	public String toString() {
		return "Cfclient [code=" + code + ", prefix=" + prefix + ", glycemie="
				+ glycemie + ", prenomNomConjoint=" + prenomNomConjoint
				+ ",aghbs=" + aghbs + ", categorie=" + categorie + ", nom="
				+ nom + ",nomprenom=" + nomprenom + ",prenomnom=" + prenomnom
				+ ", prenom=" + prenom + ", cnss=" + cnss + ", sexe=" + sexe
				+ ", civil=" + civil + ", dateNaiss=" + dateNaiss + ", rue="
				+ rue + ", village=" + village + ", pays=" + pays
				+ ", telephone=" + telephone + ", notes=" + notes
				+ ", typCons=" + typCons + ", nbCons=" + nbCons + ", dateCons="
				+ dateCons + ", datesaisie=" + datesaisie + ", ant11=" + ant11
				+ ", dpr=" + dpr + ", mariage=" + mariage + ", consang="
				+ consang + ", dureeReg=" + dureeReg + ", regles=" + regles
				+ ", dysmenorhe=" + dysmenorhe + ", mastodynie=" + mastodynie
				+ ", menopose=" + menopose + ", ant3=" + ant3 + ", dateFr="
				+ dateFr + ", resultFr=" + resultFr + ", ddr=" + ddr
				+ ", spanio=" + spanio + ", ddg=" + ddg + ", dateMoyen="
				+ dateMoyen + ", moyen=" + moyen + ", gestite=" + gestite
				+ ", partie=" + partie + ", gviv=" + gviv + ", fviv=" + fviv
				+ ", cesar=" + cesar + ", codePost=" + codePost
				+ ", telephone2=" + telephone2 + ", telC=" + telC + ", gsmC="
				+ gsmC + ", gsm1=" + gsm1 + ", gsm2=" + gsm2 + ", eMailP="
				+ eMailP + ", eMailC=" + eMailC + ", nomC=" + nomC
				+ ", prenomC=" + prenomC + ", taille=" + taille + ", poids="
				+ poids + ", gs=" + gs + ", rh=" + rh + ", dateFrotti="
				+ dateFrotti + ", resultatFrotti=" + resultatFrotti
				+ ", dateNaissC=" + dateNaissC + ", allergie=" + allergie
				+ ", notes2=" + notes2 + ", dernierVisite=" + dernierVisite
				+ ", assurance1=" + assurance1 + ", assurance2=" + assurance2
				+ ", remarque=" + remarque + " , categoriEtoile="
				+ categoriEtoile + ", tPrevu=" + tPrevu + ", tActuel="
				+ tActuel + ", toxo=" + toxo + ", tpha=" + tpha + ", rubeole="
				+ rubeole + ", nbrGarcon=" + nbrGarcon + ", nbrFille="
				+ nbrFille + ", cycleType=" + cycleType + ", regleType="
				+ regleType + ", cycle=" + cycle + ", archive=" + archive + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aghbs == null) ? 0 : aghbs.hashCode());
		result = prime * result
				+ ((allergie == null) ? 0 : allergie.hashCode());
		result = prime * result + ((ant11 == null) ? 0 : ant11.hashCode());
		result = prime * result + ((ant3 == null) ? 0 : ant3.hashCode());
		result = prime * result
				+ ((assurance1 == null) ? 0 : assurance1.hashCode());
		result = prime * result
				+ ((assurance2 == null) ? 0 : assurance2.hashCode());
		result = prime * result
				+ ((categorie == null) ? 0 : categorie.hashCode());
		result = prime * result
				+ ((categoriEtoile == null) ? 0 : categoriEtoile.hashCode());
		
		result = prime * result + cesar;
		result = prime * result + ((civil == null) ? 0 : civil.hashCode());
		result = prime * result + ((cnss == null) ? 0 : cnss.hashCode());
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result
				+ ((codePost == null) ? 0 : codePost.hashCode());
		result = prime * result + ((consang == null) ? 0 : consang.hashCode());
		result = prime * result + ((cycle == null) ? 0 : cycle.hashCode());
		result = prime * result
				+ ((cycleType == null) ? 0 : cycleType.hashCode());
		result = prime * result
				+ ((dateCons == null) ? 0 : dateCons.hashCode());
		result = prime * result + ((dateFr == null) ? 0 : dateFr.hashCode());
		result = prime * result
				+ ((dateFrotti == null) ? 0 : dateFrotti.hashCode());
		result = prime * result
				+ ((dateMoyen == null) ? 0 : dateMoyen.hashCode());
		result = prime * result
				+ ((dateNaiss == null) ? 0 : dateNaiss.hashCode());
		result = prime * result
				+ ((dateNaissC == null) ? 0 : dateNaissC.hashCode());
		result = prime * result
				+ ((datesaisie == null) ? 0 : datesaisie.hashCode());
		result = prime * result + ((ddg == null) ? 0 : ddg.hashCode());
		result = prime * result + ((ddr == null) ? 0 : ddr.hashCode());
		result = prime * result
				+ ((dernierVisite == null) ? 0 : dernierVisite.hashCode());
		result = prime * result + ((dpr == null) ? 0 : dpr.hashCode());
		result = prime * result
				+ ((dureeReg == null) ? 0 : dureeReg.hashCode());
		result = prime * result
				+ ((dysmenorhe == null) ? 0 : dysmenorhe.hashCode());
		result = prime * result + ((eMailC == null) ? 0 : eMailC.hashCode());
		result = prime * result + ((eMailP == null) ? 0 : eMailP.hashCode());
		result = prime * result + ((fviv == null) ? 0 : fviv.hashCode());
		result = prime * result + gestite;
		result = prime * result
				+ ((glycemie == null) ? 0 : glycemie.hashCode());
		result = prime * result + ((gs == null) ? 0 : gs.hashCode());
		result = prime * result + ((gsm1 == null) ? 0 : gsm1.hashCode());
		result = prime * result + ((gsm2 == null) ? 0 : gsm2.hashCode());
		result = prime * result + ((gsmC == null) ? 0 : gsmC.hashCode());
		result = prime * result + ((gviv == null) ? 0 : gviv.hashCode());
		result = prime * result + ((mariage == null) ? 0 : mariage.hashCode());
		result = prime * result
				+ ((mastodynie == null) ? 0 : mastodynie.hashCode());
		result = prime * result
				+ ((menopose == null) ? 0 : menopose.hashCode());
		result = prime * result + ((moyen == null) ? 0 : moyen.hashCode());

		result = prime * result + nbCons;
		result = prime * result + nbrFille;

		result = prime * result + nbrGarcon;
		result = prime * result + ((nom == null) ? 0 : nom.hashCode());
		result = prime * result + ((nomC == null) ? 0 : nomC.hashCode());
		result = prime * result + ((notes == null) ? 0 : notes.hashCode());
		result = prime * result + ((notes2 == null) ? 0 : notes2.hashCode());
		result = prime * result + partie;
		result = prime * result + ((pays == null) ? 0 : pays.hashCode());
		result = prime * result + ((poids == null) ? 0 : poids.hashCode());
		result = prime * result + ((prefix == null) ? 0 : prefix.hashCode());
		result = prime * result + ((prenom == null) ? 0 : prenom.hashCode());
		result = prime * result + ((prenomC == null) ? 0 : prenomC.hashCode());
		result = prime * result
				+ ((professionC == null) ? 0 : professionC.hashCode());
		result = prime * result
				+ ((professionP == null) ? 0 : professionP.hashCode());
		result = prime * result
				+ ((regleType == null) ? 0 : regleType.hashCode());
		result = prime * result + ((regles == null) ? 0 : regles.hashCode());
		result = prime * result
				+ ((remarque == null) ? 0 : remarque.hashCode());
		result = prime * result
				+ ((resultFr == null) ? 0 : resultFr.hashCode());
		result = prime * result
				+ ((resultatFrotti == null) ? 0 : resultatFrotti.hashCode());
		result = prime * result + ((rh == null) ? 0 : rh.hashCode());
		result = prime * result + ((rubeole == null) ? 0 : rubeole.hashCode());
		result = prime * result + ((rue == null) ? 0 : rue.hashCode());
		result = prime * result + ((sexe == null) ? 0 : sexe.hashCode());
		result = prime * result + (spanio ? 1231 : 1237);
		result = prime * result + ((tActuel == null) ? 0 : tActuel.hashCode());
		result = prime * result + ((tPrevu == null) ? 0 : tPrevu.hashCode());
		result = prime * result + ((taille == null) ? 0 : taille.hashCode());
		result = prime * result + ((telC == null) ? 0 : telC.hashCode());
		result = prime * result
				+ ((telephone == null) ? 0 : telephone.hashCode());
		result = prime * result
				+ ((telephone2 == null) ? 0 : telephone2.hashCode());
		result = prime * result
				+ ((nomprenom == null) ? 0 : nomprenom.hashCode());
		result = prime * result
				+ ((prenomnom == null) ? 0 : prenomnom.hashCode());

		result = prime * result + ((toxo == null) ? 0 : toxo.hashCode());
		result = prime * result + ((tpha == null) ? 0 : tpha.hashCode());
		result = prime * result + ((typCons == null) ? 0 : typCons.hashCode());
		result = prime * result + ((village == null) ? 0 : village.hashCode());
		result = prime * result + (archive ? 1231 : 1237);
		result = prime * result + (ddgCorigee ? 1231 : 1237);

		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cfclient other = (Cfclient) obj;
		if (aghbs == null) {
			if (other.aghbs != null)
				return false;
		} else if (!aghbs.equals(other.aghbs))
			return false;
		if (allergie == null) {
			if (other.allergie != null)
				return false;
		} else if (!allergie.equals(other.allergie))
			return false;
		if (categoriEtoile == null) {
			if (other.categoriEtoile != null)
				return false;
		} else if (!categoriEtoile.equals(other.categoriEtoile))
			return false;
		if (ant11 == null) {
			if (other.ant11 != null)
				return false;
		} else if (!ant11.equals(other.ant11))
			return false;
		if (ant3 == null) {
			if (other.ant3 != null)
				return false;
		} else if (!ant3.equals(other.ant3))
			return false;
		if (assurance1 == null) {
			if (other.assurance1 != null)
				return false;
		} else if (!assurance1.equals(other.assurance1))
			return false;
		if (assurance2 == null) {
			if (other.assurance2 != null)
				return false;
		} else if (!assurance2.equals(other.assurance2))
			return false;
		if (categorie == null) {
			if (other.categorie != null)
				return false;
		} else if (!categorie.equals(other.categorie))
			return false;
		if (cesar != other.cesar)
			return false;
		if (civil == null) {
			if (other.civil != null)
				return false;
		} else if (!civil.equals(other.civil))
			return false;

		if (prenomNomConjoint == null) {
			if (other.prenomNomConjoint != null)
				return false;
		} else if (!prenomNomConjoint.equals(other.prenomNomConjoint))
			return false;

		if (cnss == null) {
			if (other.cnss != null)
				return false;
		} else if (!cnss.equals(other.cnss))
			return false;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (codePost == null) {
			if (other.codePost != null)
				return false;
		} else if (!codePost.equals(other.codePost))
			return false;
		if (consang == null) {
			if (other.consang != null)
				return false;
		} else if (!consang.equals(other.consang))
			return false;
		if (cycle == null) {
			if (other.cycle != null)
				return false;
		} else if (!cycle.equals(other.cycle))
			return false;
		if (cycleType == null) {
			if (other.cycleType != null)
				return false;
		} else if (!cycleType.equals(other.cycleType))
			return false;
		if (dateCons == null) {
			if (other.dateCons != null)
				return false;
		} else if (!dateCons.equals(other.dateCons))
			return false;
		if (dateFr == null) {
			if (other.dateFr != null)
				return false;
		} else if (!dateFr.equals(other.dateFr))
			return false;
		if (dateFrotti == null) {
			if (other.dateFrotti != null)
				return false;
		} else if (!dateFrotti.equals(other.dateFrotti))
			return false;
		if (dateMoyen == null) {
			if (other.dateMoyen != null)
				return false;
		} else if (!dateMoyen.equals(other.dateMoyen))
			return false;
		if (dateNaiss == null) {
			if (other.dateNaiss != null)
				return false;
		} else if (!dateNaiss.equals(other.dateNaiss))
			return false;
		if (dateNaissC == null) {
			if (other.dateNaissC != null)
				return false;
		} else if (!dateNaissC.equals(other.dateNaissC))
			return false;
		if (datesaisie == null) {
			if (other.datesaisie != null)
				return false;
		} else if (!datesaisie.equals(other.datesaisie))
			return false;
		if (ddg == null) {
			if (other.ddg != null)
				return false;
		} else if (!ddg.equals(other.ddg))
			return false;
		if (ddr == null) {
			if (other.ddr != null)
				return false;
		} else if (!ddr.equals(other.ddr))
			return false;
		if (dernierVisite == null) {
			if (other.dernierVisite != null)
				return false;
		} else if (!dernierVisite.equals(other.dernierVisite))
			return false;
		if (dpr == null) {
			if (other.dpr != null)
				return false;
		} else if (!dpr.equals(other.dpr))
			return false;
		if (dureeReg == null) {
			if (other.dureeReg != null)
				return false;
		} else if (!dureeReg.equals(other.dureeReg))
			return false;
		if (dysmenorhe == null) {
			if (other.dysmenorhe != null)
				return false;
		} else if (!dysmenorhe.equals(other.dysmenorhe))
			return false;
		if (eMailC == null) {
			if (other.eMailC != null)
				return false;
		} else if (!eMailC.equals(other.eMailC))
			return false;
		if (eMailP == null) {
			if (other.eMailP != null)
				return false;
		} else if (!eMailP.equals(other.eMailP))
			return false;
		if (fviv == null) {
			if (other.fviv != null)
				return false;
		} else if (!fviv.equals(other.fviv))
			return false;
		if (gestite != other.gestite)
			return false;
		if (glycemie == null) {
			if (other.glycemie != null)
				return false;
		} else if (!glycemie.equals(other.glycemie))
			return false;
		if (gs == null) {
			if (other.gs != null)
				return false;
		} else if (!gs.equals(other.gs))
			return false;
		if (gsm1 == null) {
			if (other.gsm1 != null)
				return false;
		} else if (!gsm1.equals(other.gsm1))
			return false;
		if (gsm2 == null) {
			if (other.gsm2 != null)
				return false;
		} else if (!gsm2.equals(other.gsm2))
			return false;
		if (gsmC == null) {
			if (other.gsmC != null)
				return false;
		} else if (!gsmC.equals(other.gsmC))
			return false;
		if (gviv == null) {
			if (other.gviv != null)
				return false;
		} else if (!gviv.equals(other.gviv))
			return false;
		if (mariage == null) {
			if (other.mariage != null)
				return false;
		} else if (!mariage.equals(other.mariage))
			return false;
		if (mastodynie == null) {
			if (other.mastodynie != null)
				return false;
		} else if (!mastodynie.equals(other.mastodynie))
			return false;
		if (menopose == null) {
			if (other.menopose != null)
				return false;
		} else if (!menopose.equals(other.menopose))
			return false;
		if (moyen == null) {
			if (other.moyen != null)
				return false;
		} else if (!moyen.equals(other.moyen))
			return false;

		if (nbCons != other.nbCons)
			return false;

		if (nbrFille != other.nbrFille)
			return false;
		if (nbrGarcon != other.nbrGarcon)
			return false;
		if (nom == null) {
			if (other.nom != null)
				return false;
		} else if (!nom.equals(other.nom))
			return false;
		if (nomC == null) {
			if (other.nomC != null)
				return false;
		} else if (!nomC.equals(other.nomC))
			return false;
		if (notes == null) {
			if (other.notes != null)
				return false;
		} else if (!notes.equals(other.notes))
			return false;
		if (notes2 == null) {
			if (other.notes2 != null)
				return false;
		} else if (!notes2.equals(other.notes2))
			return false;
		if (partie != other.partie)
			return false;
		if (pays == null) {
			if (other.pays != null)
				return false;
		} else if (!pays.equals(other.pays))
			return false;
		if (poids == null) {
			if (other.poids != null)
				return false;
		} else if (!poids.equals(other.poids))
			return false;
		if (prefix == null) {
			if (other.prefix != null)
				return false;
		} else if (!prefix.equals(other.prefix))
			return false;
		if (prenom == null) {
			if (other.prenom != null)
				return false;
		} else if (!prenom.equals(other.prenom))
			return false;
		if (prenomC == null) {
			if (other.prenomC != null)
				return false;
		} else if (!prenomC.equals(other.prenomC))
			return false;
		if (professionC == null) {
			if (other.professionC != null)
				return false;
		} else if (!professionC.equals(other.professionC))
			return false;
		if (professionP == null) {
			if (other.professionP != null)
				return false;
		} else if (!professionP.equals(other.professionP))
			return false;
		if (regleType == null) {
			if (other.regleType != null)
				return false;
		} else if (!regleType.equals(other.regleType))
			return false;
		if (regles == null) {
			if (other.regles != null)
				return false;
		} else if (!regles.equals(other.regles))
			return false;
		if (remarque == null) {
			if (other.remarque != null)
				return false;
		} else if (!remarque.equals(other.remarque))
			return false;
		if (resultFr == null) {
			if (other.resultFr != null)
				return false;
		} else if (!resultFr.equals(other.resultFr))
			return false;
		if (resultatFrotti == null) {
			if (other.resultatFrotti != null)
				return false;
		} else if (!resultatFrotti.equals(other.resultatFrotti))
			return false;
		if (rh == null) {
			if (other.rh != null)
				return false;
		} else if (!rh.equals(other.rh))
			return false;
		if (rubeole == null) {
			if (other.rubeole != null)
				return false;
		} else if (!rubeole.equals(other.rubeole))
			return false;
		if (rue == null) {
			if (other.rue != null)
				return false;
		} else if (!rue.equals(other.rue))
			return false;
		if (sexe == null) {
			if (other.sexe != null)
				return false;
		} else if (!sexe.equals(other.sexe))
			return false;
		if (spanio != other.spanio)
			return false;
		if (tActuel == null) {
			if (other.tActuel != null)
				return false;
		} else if (!tActuel.equals(other.tActuel))
			return false;
		if (tPrevu == null) {
			if (other.tPrevu != null)
				return false;
		} else if (!tPrevu.equals(other.tPrevu))
			return false;
		if (taille == null) {
			if (other.taille != null)
				return false;
		} else if (!taille.equals(other.taille))
			return false;
		if (telC == null) {
			if (other.telC != null)
				return false;
		} else if (!telC.equals(other.telC))
			return false;
		if (telephone == null) {
			if (other.telephone != null)
				return false;
		} else if (!telephone.equals(other.telephone))
			return false;
		if (telephone2 == null) {
			if (other.telephone2 != null)
				return false;
		} else if (!telephone2.equals(other.telephone2))
			return false;
		if (toxo == null) {
			if (other.toxo != null)
				return false;
		} else if (!toxo.equals(other.toxo))
			return false;
		if (tpha == null) {
			if (other.tpha != null)
				return false;
		} else if (!tpha.equals(other.tpha))
			return false;
		if (typCons == null) {
			if (other.typCons != null)
				return false;
		} else if (!typCons.equals(other.typCons))
			return false;
		if (village == null) {
			if (other.village != null)
				return false;
		} else if (!village.equals(other.village))
			return false;
		if (archive != other.archive)
			return false;
		if (ddgCorigee != other.ddgCorigee)
			return false;
		return true;
	}

	public String getPrenomNomConjoint() {
		return prenomNomConjoint;
	}

	public void setPrenomNomConjoint(String prenomNomConjoint) {
		this.prenomNomConjoint = prenomNomConjoint;
	}

	public boolean isDdgCorigee() {
		return ddgCorigee;
	}

	public void setDdgCorigee(boolean ddgCorigee) {
		this.ddgCorigee = ddgCorigee;
	}

	public String getCategoriEtoile() {
		return categoriEtoile;
	}

	public void setCategoriEtoile(String categoriEtoile) {
		this.categoriEtoile = categoriEtoile;
	}
	

}
