package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Clinique generated by hbm2java
 */
public class Clinique implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idclinique;
	private String libclinique;
	private Set<Cfclient> cfclients = new HashSet<Cfclient>(0);

	public Clinique() {
	}

	public Clinique(String libclinique) {
		this.libclinique = libclinique;
	}

	public Clinique(String libclinique, Set<Cfclient> cfclients) {
		this.libclinique = libclinique;
		this.cfclients = cfclients;
	}

	public Integer getIdclinique() {
		return this.idclinique;
	}

	public void setIdclinique(Integer idclinique) {
		this.idclinique = idclinique;
	}

	public String getLibclinique() {
		return this.libclinique;
	}

	public void setLibclinique(String libclinique) {
		this.libclinique = libclinique;
	}

	

	@Override
	public String toString() {
		return "Clinique [idclinique=" + idclinique + ", libclinique="
				+ libclinique + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idclinique == null) ? 0 : idclinique.hashCode());
		result = prime * result
				+ ((libclinique == null) ? 0 : libclinique.hashCode());
		return result;
	}

	public Set<Cfclient> getCfclients() {
		return cfclients;
	}

	public void setCfclients(Set<Cfclient> cfclients) {
		this.cfclients = cfclients;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Clinique other = (Clinique) obj;
		if (idclinique == null) {
			if (other.idclinique != null)
				return false;
		} else if (!idclinique.equals(other.idclinique))
			return false;
		if (libclinique == null) {
			if (other.libclinique != null)
				return false;
		} else if (!libclinique.equals(other.libclinique))
			return false;
		return true;
	}

}
