package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EtatBebe generated by hbm2java
 */
public class EtatBebe implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idetatBebe;
	private String etatBebe;
	private boolean incrementation;
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((cfclients == null) ? 0 : cfclients.hashCode());
		result = prime * result
				+ ((etatBebe == null) ? 0 : etatBebe.hashCode());
		result = prime * result
				+ ((idetatBebe == null) ? 0 : idetatBebe.hashCode());
		result = prime * result + (incrementation ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EtatBebe other = (EtatBebe) obj;
		if (cfclients == null) {
			if (other.cfclients != null)
				return false;
		} else if (!cfclients.equals(other.cfclients))
			return false;
		if (etatBebe == null) {
			if (other.etatBebe != null)
				return false;
		} else if (!etatBebe.equals(other.etatBebe))
			return false;
		if (idetatBebe == null) {
			if (other.idetatBebe != null)
				return false;
		} else if (!idetatBebe.equals(other.idetatBebe))
			return false;
		if (incrementation != other.incrementation)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "EtatBebe [idetatBebe=" + idetatBebe + ", etatBebe=" + etatBebe
				+ ", incrementation=" + incrementation + ", cfclients="
				+ cfclients + "]";
	}

	public boolean isIncrementation() {
		return incrementation;
	}

	public void setIncrementation(boolean incrementation) {
		this.incrementation = incrementation;
	}

	private Set<Cfclient> cfclients = new HashSet<Cfclient>(0);

	public EtatBebe() {
	}

	public EtatBebe(String etatBebe) {
		this.etatBebe = etatBebe;
	}

	public EtatBebe(String etatBebe, Set<Cfclient> cfclients) {
		this.etatBebe = etatBebe;
		this.cfclients = cfclients;
	}

	public Integer getIdetatBebe() {
		return this.idetatBebe;
	}

	public void setIdetatBebe(Integer idetatBebe) {
		this.idetatBebe = idetatBebe;
	}

	public String getEtatBebe() {
		return this.etatBebe;
	}

	public void setEtatBebe(String etatBebe) {
		this.etatBebe = etatBebe;
	}

	public Set<Cfclient> getCfclients() {
		return this.cfclients;
	}

	public void setCfclients(Set<Cfclient> cfclients) {
		this.cfclients = cfclients;
	}

}
