package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Doctor generated by hbm2java
 */
public class Horaire implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHoraire;
	private Date debut;
	private Date fin;
	
	public Horaire() {
	}
	
	public Horaire(Date debut, Date fin) {
		this.debut = debut;
		this.fin = fin;
	}
	
	public Integer getIdHoraire() {
		return idHoraire;
	}
	public void setIdHoraire(Integer idHoraire) {
		this.idHoraire = idHoraire;
	}
	public Date getDebut() {
		return debut;
	}
	public void setDebut(Date debut) {
		this.debut = debut;
	}
	public Date getFin() {
		return fin;
	}
	public void setFin(Date fin) {
		this.fin = fin;
	}
	
	@SuppressWarnings("deprecation")
	public static String Time(Date d){
		String time = "";
		if(d.getHours()<10)time=time+"0"+d.getHours();
		else time=time+d.getHours();
		if(d.getMinutes()<10)time=time+":0"+d.getMinutes();
		else time=time+":"+d.getMinutes();
		return time;
	}
	
	@Override
	public String toString() {
		String d, f;
		d = Time(debut);
		f = Time(fin);
		return "["+d+" - "+f+"]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((debut == null) ? 0 : debut.hashCode());
		result = prime * result + ((fin == null) ? 0 : fin.hashCode());
		result = prime * result + ((idHoraire == null) ? 0 : idHoraire.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Horaire other = (Horaire) obj;
		if (debut == null) {
			if (other.debut != null)
				return false;
		} else if (!debut.equals(other.debut))
			return false;
		if (fin == null) {
			if (other.fin != null)
				return false;
		} else if (!fin.equals(other.fin))
			return false;
		if (idHoraire == null) {
			if (other.idHoraire != null)
				return false;
		} else if (!idHoraire.equals(other.idHoraire))
			return false;
		return true;
	}
	
	@SuppressWarnings("deprecation")
	public boolean contien(Date date){
		Date debut = this.debut;
		Date fin = this.fin;
		debut.setYear(date.getYear());
		debut.setMonth(date.getMonth());
		debut.setDate(date.getDate());
		fin.setYear(date.getYear());
		fin.setMonth(date.getMonth());
		fin.setDate(date.getDate());
		return ((date.after(debut))||date.equals(debut))&&date.before(fin);
	}
}
