package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Profession generated by hbm2java
 */
public class Profession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idprofession == null) ? 0 : idprofession.hashCode());
		result = prime * result
				+ ((libprofession == null) ? 0 : libprofession.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Profession other = (Profession) obj;
		if (idprofession == null) {
			if (other.idprofession != null)
				return false;
		} else if (!idprofession.equals(other.idprofession))
			return false;
		if (libprofession == null) {
			if (other.libprofession != null)
				return false;
		} else if (!libprofession.equals(other.libprofession))
			return false;
		return true;
	}

	private Integer idprofession;
	private String libprofession;
	private Set<Cfclient> cfclientsForProfesscp = new HashSet<Cfclient>(0);
	private Set<Cfclient> cfclientsForProfessp = new HashSet<Cfclient>(0);

	public Profession() {
	}

	public Profession(String libprofession) {
		this.libprofession = libprofession;
	}

	@Override
	public String toString() {
		return "Profession [idprofession=" + idprofession + ", libprofession="
				+ libprofession + "]";
	}

	public Profession(String libprofession,
			Set<Cfclient> cfclientsForProfesscp,
			Set<Cfclient> cfclientsForProfessp) {
		this.libprofession = libprofession;
		this.cfclientsForProfesscp = cfclientsForProfesscp;
		this.cfclientsForProfessp = cfclientsForProfessp;
	}

	public Integer getIdprofession() {
		return this.idprofession;
	}

	public void setIdprofession(Integer idprofession) {
		this.idprofession = idprofession;
	}

	public String getLibprofession() {
		return this.libprofession;
	}

	public void setLibprofession(String libprofession) {
		this.libprofession = libprofession;
	}

	public Set<Cfclient> getCfclientsForProfesscp() {
		return this.cfclientsForProfesscp;
	}

	public void setCfclientsForProfesscp(Set<Cfclient> cfclientsForProfesscp) {
		this.cfclientsForProfesscp = cfclientsForProfesscp;
	}

	public Set<Cfclient> getCfclientsForProfessp() {
		return this.cfclientsForProfessp;
	}

	public void setCfclientsForProfessp(Set<Cfclient> cfclientsForProfessp) {
		this.cfclientsForProfessp = cfclientsForProfessp;
	}

}
