package com.doctor.persistance;

// Generated 18 ao�t 2014 11:50:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Ville generated by hbm2java
 */
public class Ville implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idville;
	private String ville;
	
	
	
	private Set<Cfclient> cfclients = new HashSet<Cfclient>(0);

	public Ville() {
	}

	public Ville(String ville) {
		this.ville = ville;
	}

	public Ville(String ville, Set<Cfclient> cfclients) {
		this.ville = ville;
		this.cfclients = cfclients;
	}

	public Integer getIdville() {
		return this.idville;
	}

	public void setIdville(Integer idville) {
		this.idville = idville;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set<Cfclient> getCfclients() {
		return this.cfclients;
	}

	public void setCfclients(Set<Cfclient> cfclients) {
		this.cfclients = cfclients;
	}

}
